### ISSUE TITLE
Set tab_width to indent_size by default

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig#11]
If a value is found for `indent_size` but `tab_width` has no defined value, `tab_width` should be set to the value of `indent_size`.

**Comment by leandro-lucarella-sociomantic** [comment]
I think this might not be the best idea, because you can't specify a default for all files to use spaces as tab and a `indent_size` and then make an exception for makefiles (which need tab to indent) without messing with the user's `tab_width` (which you don't want to impose as the whole beauty of using tabs is every user can configure the width differently without interfering with each other).

See #262

**Comment by xuhdev** [comment]
@leandro-lucarella-sociomantic If you want to use tab as the indentation symbol, you can choose to not specify `indent_size`... So I don't see a problem here.

**Comment by leandro-lucarella-sociomantic** [comment]
See #262.
