### ISSUE TITLE
Read closest EditorConfig files last

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig#14]
Any properties specified in closer EditorConfig file should take precedence over more distant EditorConfig files.

**Comment by tonur** [comment]
Would it be possible to support sections that does not listen to precedence in the closer EditorConfig file?

Given an example:
I have a file: "\~/.editorconfig" that mentions the following:
```
# top-most EditorConfig file
root = true

[*]
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{.git**,*.pfx}]
charset = unset
end_of_line = unset
insert_final_newline = unset
trim_trailing_whitespace = unset
indent_style = unset
indent_size = unset
```

Then, in a repository that I use to collaborate with others, we have the following file: "\~/projects/my-collaborative-project/.editorconfig" that has the following:
```
[*]
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

# Should match "go fmt"
[*{.go}]
indent_style = tab
indent_size = 4
```

I really want the settings in "\~/.editorconfig" regarding files with ".git/\*" and "\*.pfx" to take effect, since my IDE is complaining about .editorconfig violations in these files.
This is of course due to my "\~/projects/my-collaborative-project/.editorconfig" saying that I have a "*" defined and set rules for every file. But I want a certain section in the root to take precedence.

Is this something I could create an issue requesting this functionality?

Perhaps a property that is called "precedence" that could be set to "use_parent_setting"?

Or perhaps a way to specify files not previously defined, like so:
```
[%*] # "%*" means apply to any file unless other rules specify other properties.
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

Sorry to piggieback off an old issue, but the fix in https://github.com/editorconfig/editorconfig/commit/4f21a9c127e801be2bbd20600efb06e9472d2d90 is the one causing headaches for me.

**Comment by xuhdev** [comment]
You can append the following to the project `.editorconfig`:

```
[.git/*]
charset = unset
trim_trailing_whitespace = unset
insert_final_newline = unset
```

Or, you can add the following to the `.git` dir:

```
root = true
```

(Your project editorconfig file should contain `root = true`, otherwise your IDE may behave inconsistently from your teammates' IDE due to the presence of `~/.editorconfig`.)
