### ISSUE TITLE
[Win32] another problem with fnmatch()

### ISSUE THREAD

**Issue by k-takata** [editorconfig/editorconfig#144]
(Sorry for opening a new issue, I couldn't reopen #125.)
The fix for #125 caused another problem.

`fnmatch()` doesn't work properly when a directory is used in a pattern.
E.g.

``` ini
[Bar/*]
indent_style = space
```

If the `.editorconfig` is in `C:\Foo` and when opening `C:\Foo\Bar\Baz.txt`,
`fnmatch()` will be called with the following arguments:

```
name: C:\Foo\Bar\Baz.txt
pat:  c:/foo/Bar/*     (Note that only 'c:/foo' is lower case.)
```

Of course, this should match but currently it doesn't.
Both `name` and `pat` should be converted to lower case.
My previous patch does this conversion properly.
Or, another implementation would be:

``` python
    name = os.path.normcase(name).replace(os.sep, "/")
    pat = os.path.normcase(pat).replace(os.sep, "/")
    return fnmatchcase(name, pat)
```

**Comment by awsdert** [comment]
Wouldn't the simplest fix be to just provide an option to the user to just search with case insensitive option of fnmatch()? There's no reason that software should _only_ provide one or the other, just do sensitive by default but always present an option to do the slower in-sensitive method.

**Comment by xuhdev** [comment]
@awsdert I'm not sure what you are trying to say. Do you mean there should be an option to allow users to toggle the case-sensitivity?

The `.editorconfig` files are meant to be interpreted in one way, since it is intended to help team members to maintain a consistent coding style. If a user can change how these files are interpreted on their ends alone, it defeats the purpose of this project.

**Comment by awsdert** [comment]
Then just provide the parameter in the editor config a **user** defined config. Just because the config is shared doesn't change that a user has to fill it at some point, even if that user is the owner of the project that's using an editor config.
