### ISSUE TITLE
Add MonoDevelop plugin

### ISSUE THREAD

**Issue by deniz1a** [editorconfig/editorconfig#158]
Hello, I am using MonoDevelop on linux and it appears there isn't an editorconfig plugin for this. Are VisualStudio and MonoDevelop plugins compatible?
Thanks.
##

**Comment by rob100** [comment]
I am really interested in an editorconfig plugin for MonoDevelop. Perhaps I can also contribute something to this. But before I start working more on this topic, I wanted to ask what the current status is. Is somebody already working on this?

**Comment by Mpdreamz** [comment]
Go for it! We now also have a pure .net version of editorconfig core that the monodevelop addin could use.

**Comment by rob100** [comment]
Ok, I will take a further look into this and check if I can develop an addin with my current skills.

**Comment by kzu** [comment]
Would love to see this provided for Xamarin Studio. If you do, please do let the team know at https://bugzilla.xamarin.com/show_bug.cgi?id=22576 :)

**Comment by rob100** [comment]
There was a lot of change with MonoDevelop becoming Xamarin Studio. At the moment there will be no further activities from my side developing a plugin for Xamarin Studio.

**Comment by mikerochip** [comment]
Necroing this thread, but I just finished making one of these: https://github.com/mikerochip/editorconfig-monodevelop

Lots has changed since this thread was created e.g. Visual Studio for Mac becoming a thing. It's mostly targeting that IDE honestly since it seems MonoDevelop proper is dying.

**Comment by mikerochip** [comment]
Also, since it seems that user uploads to a MonoDevelop/Visual Studio for Mac addin repo have been effectively disabled, I emailed mhutch@microsoft.com to see if I can get that revived so EditorConfig can be pulled from Visual Studio for Mac's Extension Manager.

I also filled out the survey at the bottom of this page and am awaiting a response:
https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac

In the meantime, it would be nice if my project could be moved into the editorconfig organization proper. Maybe some traction could be made on getting this put into the extension gallery if it were in an organization and not just some random person's side project?

**Comment by mhutch** [comment]
Thanks @mikerochip for developing this extension!

We're [integrating ](https://github.com/mono/monodevelop/tree/editorconfig)EditorConfig support into MonoDevelop core in the upcoming 7.5 release but this should help folks who want to use it on older versions 😃

**Comment by mikerochip** [comment]
Ah hahaha, wow, I feel like a dummy! I guess my searches for EditorConfig + MonoDevelop were not as exhaustive as they should've been. Thanks for letting me know!

**Comment by mhutch** [comment]
@mikerochip that's on us, sorry, we hadn't talked about it publicly at all despite the branch being public. Hopefully our switch to GitHub issues makes this kind of stuff more obvious in future.

**Comment by mikerochip** [comment]
Just to give an update to anyone still interested in this: my EditorConfig addin should now be available in the extension manager of MonoDevelop and Visual Studio for Mac, mostly due to the help of @mhutch. Minimum version is 7.3, so this should tide people over until the official support is released.

Here's the source one more time: https://github.com/mikerochip/editorconfig-monodevelop

**Comment by xuhdev** [comment]
@mikerochip That's awesome, thanks! @ineptcat  @Pittan Would you like to help out :smiley: ? Thank you again!

**Comment by xuhdev** [comment]
Let me close this: Will move the website icon to a different issue.
