### ISSUE TITLE
[Visual Studio] support charset property

### ISSUE THREAD

**Issue by sigod** [editorconfig/editorconfig#164]

**Comment by dliuzzi** [comment]
I am also very interested in this. BOMs are a real pain in source control, as they clutter diffs.

Unfortunately I have zero experience coding VS extensions, but there is an extension called *[Fix File Encoding](https://visualstudiogallery.msdn.microsoft.com/540ac2d8-f881-4794-8b00-810d28257b70)* which removes the BOM when files are saved.

Although the extension works, integrating this functionally with EditorConfig's `charset` property would be great as this would then become a part of the *project* configuration (automatic) instead of system configuration (manual).

**Comment by jedmao** [comment]
That extension should be called Strip BOM, like [the Node equivalent](https://www.npmjs.com/package/strip-bom). In fact, supporting charset is much more complicated than stripping BOMs. You have to also add BOMs where needed and convert encodings as well. Not saying it can't be done, but it's a lot of work.

**Comment by Mpdreamz** [comment]
This is now implemented in `master` of visual studio extension:

https://github.com/editorconfig/editorconfig-visualstudio/pull/44
