### ISSUE TITLE
error with vim when editing using netrw

### ISSUE THREAD

**Issue by romeovs** [editorconfig/editorconfig#196]
When I'm trying to edit a file over `scp` with vim I get an error complaining about the pathname of the file.

```
vim scp://myserver/myfile.txt
```
gives the following error:

```
Error detected while processing function <SNR>54_UseConfigFiles..<SNR>54_UseConfigFiles_Python_Builtin:
line   23:
Input file must be a full path name.
```

**Comment by xuhdev** [comment]
Dup of #101. Please follow there.

**Comment by romeovs** [comment]
I don't see how this is a duplicate of #101 ?

**Comment by xuhdev** [comment]
EditorConfig plugins replies on the core library to read and parse the `.editorconfig` files. After parsing, the plugin sets proper settings in the editor according to the output of the parsing. Your case is that the file locates on a remote system, which fails to work because the lack of support of EditorConfig core on remote file system, which is #101.

As a temporary workaround, you can use `sshfs` to mount remote file system locally. However, it may not be as convenient as netrw though.

**Comment by xuhdev** [comment]
You can also use the new option `g:EditorConfig_execlude_patterns` to ignore any remote ssh files:

    let g:EditorConfig_execlude_patterns = ['scp://.*']
