### ISSUE TITLE
editorconfig-vim - Support python3 only

### ISSUE THREAD

**Issue by LordAro** [editorconfig/editorconfig#197]
My vim install only comes with python3 support ("-python +python3")

Currently on load it just comes up with the default message:
`EditorConfig: No EditorConfig Core is available. The plugin won't work.`

As far as i can tell, editorconfig-vim supports python3 (there's even a compat.py).
I don't know how vim plugins work with python2/3, but it seems to me that it shouldn't be difficult to allow it to load if vim has python3 support?
##

**Comment by xuhdev** [comment]
No, it's not difficult, but it seems ugly to implement. If you check `plugins/editorconfig.vim`, you will see some embedded python scripts surrounded by `python`. If one needs to use python3, these python must be replaced by `python3`. The python code is supposed to work on both python and python3, so it should not be a problem to replace. But to support both version, the code has to be basically copied twice, which is ugly.

If you don't want to touch the plugin code and want to use EditorConfig, you can install the [C version EditorConfig core](https://github.com/editorconfig/editorconfig-core-c), and set `g:EditorConfig_core_mode` to `"external_command"` (see `:h g:EditorConfig_core_mode`). Let me know if you still have problems :)

**Comment by xuhdev** [comment]
Actually I'm also considering completely removing the python support in the Vim plugin (due to Vim's poor maintenance of its python integration). What we can do is to build the C version statistically for multiple platforms and include the compiled version in the plugin package. This is somewhat similar to the MediaWiki plugin [Scribunto](https://www.mediawiki.org/wiki/Extension:Scribunto) which bundles a statically compiled lua binary for common platforms.

**Comment by cxw42** [comment]
I am going to close this issue since it has been inactive for a long time.  If you are still having trouble, would you please open an issue at https://github.com/editorconfig/editorconfig-vim/issues ?  Thanks!
