### ISSUE TITLE
Detect typos

### ISSUE THREAD

**Issue by wernight** [editorconfig/editorconfig#224]
editorconfig-core-py and may be other helper libraries could report warnings like typos.

Best would be if it had a list of known properties, but supposing one would like to allow extending editconfig with any random name, it would still be possible by checking if Levenshtein distance is 1 or 2 to any known property.

Example:

`indend_style` is Levenshtein distance 1 of `indent_style`, so editorconfig-core-py could output:

    indend_style = tab
    # WARN indend_style property is not known, did you mean indent_style?

For Levenshtein distance > 3 it could just ignore to allow for example someone to put random_property_name in `.editorconfig` without getting a warning.

PS: I could help writing that function that would use [the python implementation](https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Python) and check against all known properties, or something a bit more efficient if needed.

Related to https://github.com/editorconfig/editorconfig-vim/issues/40#issuecomment-118086688

**Comment by xuhdev** [comment]
@wernight I don't think this should be something in the core though. I would prefer writing an independent tool to detect the "typos", for the following reasons:

- We have a lot of EditorConfig cores (C, Python, JavaScript, Java, Ruby). This feature isn't an essential feature of the cores, we can simply write an independent tool to do this task, instead of implementing it 5 times.
- Editors can define their own extensions of EditorConfig properties, and it is not supposed to output noises (of course, we can add a switch to solve this). Writing an independent tool would be more flexible.

I would use Python to write a simple tool to do this. If you disagree with my opinion, please let me know.

**Comment by xuhdev** [comment]
I have added a typo checking script now: https://github.com/editorconfig/utilities/tree/master/check-typos

**Comment by wernight** [comment]
SGTM
