### ISSUE TITLE
Document linter overlaps?

### ISSUE THREAD

**Issue by kevinSuttle** [editorconfig/editorconfig#244]
Noticing a few overlaps with things like ESLint. Is this documented somewhere, or is there a best practice on what to use where? 

cc: @nzakas

**Comment by jedmao** [comment]
The whole idea of EditorConfig is not to lint, but to set your editor's settings appropriately for each file you open and edit. This is language-agnostic and shouldn't care or be aware of the language in a particular file.

Linting, however, is a totally separate concern and is quite language-specific. Use JS linting tools for JS and Python linting tools for Python, but it has nothing to do with EditorConfig.

**Comment by kevinSuttle** [comment]
I know the differences, but there are overlaps. Specifically around spacing, and other non-specific settings. AFAICT, there's no way of knowing which is applied when, and which one takes precedence.

**Comment by jedmao** [comment]
But ESLint doesn't change your editor settings, so what do you mean when you say "which one is applied when"?

EditorConfig settings are applied to your editor whenever you open a file or file tab, but nothing is checked while you're editing the file.

ESLint settings are "checked" while you edit the file and potentially via the command line as well.

Again, totally different tools. EditorConfig applies settings. ESLint checks that files adhere to settings.

**Comment by kevinSuttle** [comment]
Ok, that makes it a bit more understandable. Thanks @jedmao.

**Comment by kevinSuttle** [comment]
Tangent: do you have suggestions for how to make the settings across linters, editorConfig and IDE DRY? @sindresorhus ? 

**.editorConfig**
```
trim_trailing_whitespace = true
```

**.eslintrc**
```
no-trailing-spaces: 0
```

**Sublime Text prefs**
```
"trim_trailing_white_space_on_save": true
```

**Comment by jedmao** [comment]
Are your IDE settings project-specific or global?

**Comment by kevinSuttle** [comment]
Global.

**Comment by mathiasbynens** [comment]
If you use a global `.editorconfig` file (e.g. in `~`, assuming all your documents match `~/**`), and you install the EditorConfig Sublime Text plugin, there’s no need to have the Sublime Text prefs there.

The remaining problem is syncing `.editorconfig` with `.eslintrc`.

**Comment by kevinSuttle** [comment]
@mathiasbynens See #245 and https://github.com/editorconfig/editorconfig-core-js/issues/30

**Comment by jedmao** [comment]
Since EditorConfig settings are project and potentially folder or file-specific and your ST3 settings are global, I wouldn't call that repeating yourself.

As for `.editorconfig` and `.eslintrc`, I suppose it depends on the type of project you're running. If it's a JavaScript project with a `package.json` file then [the issue you posted before](https://github.com/editorconfig/editorconfig-core-js/issues/30) wouldn't even fix the problem, because you might have both "eclintConfig" and "editorConfig" sections in the same JSON file.

Even if you could get this working on a project level, that still doesn't solve folder or file-specific EditorConfig settings. You can scatter multiple `.editorConfig` files and multiple `.eslintrc` files throughout folders in your project, so I really can't think of a graceful way to simplify this process.

My advice is to accept the fact that the ROI in this case is just not worth it and to go ahead and place both files in whatever folders you need and move on.
