### ISSUE TITLE
Add new properties: the general rule

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#277]
I've proposed a new way to add new **universal** properties long time ago, to boost the development of the EditorConfig specification: https://groups.google.com/forum/#!topic/editorconfig/oXw7tYPNUbE

However, this has never been done, except for that the [wiki page](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties) has been created. If all of you agree with the following (no opposing in ONE week, that is, until Nov 30 GMT 23:59), I'm gonna do the following:

- Create a contribution guideline for the wiki page linked above in this repo, stating that
  - To add a new property or new value, post on the issue list first, and wait for 2 weeks discussion. If there's no objection, we will add it.
  - When adding any new properties and values, we note the first supported version number in the date format, e.g., `20161102`. This also allows us to add new properties or values at any moment (more flexibility), without making specific releases to support a bulk of them. If it is supported by any editors, add them to the list.

- In the homepage, add a link to the wiki page, stating that the full list of properties and values is there.
- (Re)-create some issues stating the possibility of some new properties and values in some old issues, and follow the procedure described above to discuss them and possibly add to the wiki page.

@editorconfig

**Comment by xuhdev** [comment]
In addition, a blog post to announce this no rule...

**Comment by treyhunner** [comment]
I like this idea. Thank you for taking a lead on this.

I'm a little concerned about the 2 weeks discussion and post with no objection, but I don't know a good way around that since we don't have a concrete team/group who are always available.

+1 from me.

**Comment by xuhdev** [comment]
@treyhunner For your concern, can we make a small board member that everyone in this board must show the agreement? For others, since we cannot guarantee their availability, we take them as agreed if no objection is proposed.

**Comment by florianb** [comment]
I dislike the idea that EditorConfig moves away from the editors domain to the languages-domain. In my opinion this is getting barely maintainable.

It is one thing to define if an editor should insert line-endings as a newline or a carriage return. But trying to create a unite config-format across all languages may become a big mess for a few reasons.

Take the quote_types as an example. Many languages offer different quote types because they offer different functionality (f.e. single quotes for raw strings, double quotes for template-strings). It is suggested that any tools may deal with this property. But dealing with it would need to have contextual information, f.e. an AST to prove if the required behavior is valid.

This functionality is already implemented in linters & co. And their configuration-possibilities are pretty complex and (even for some well known rules like the eslint `quote` rule) still changing.

---

I would prefer to see that this standard gets more explicit (leaving less room for interpretation how EditorConfig works) and more mature in a sense of overthinking the desired behavior of the rules and what to expect from the different implementations.

**Comment by xuhdev** [comment]
@florianb I edited the original post to be explicit that we are currently for **universal** properties only. Thanks for pointing out the ambiguity.

**Comment by florianb** [comment]
Thanks for picking that up @xuhdev.

**Comment by florianb** [comment]
You probably could consider founding a board of active members where everybody has to vote.

Leaving the final decision to missing objections raises the danger of introducing unwanted changes.

**Comment by xuhdev** [comment]
@florianb I'm gonna delay the process to Nov 15 for now. We should consider how to form the small board.

**Comment by florianb** [comment]
If i can be of any help -- let me know.

**Comment by treyhunner** [comment]
I'm for a board in theory but how to form one is a concern. Democracy is unfortunately difficult to implement in open community situations.

I think it might make the most sense to have the board be self-appointed: current members decide to add others. If someone is interested in having a voice, we can vote whether we'd like to give them one. In general I'd personally like to empower almost anyone who would like to help out as EditorConfig is not as high on my priority list as it once was.

**Comment by xuhdev** [comment]
To keep the project healthy and active, I believe an organized democracy which grants power to the community is necessary.

Let's try this (don't hesitate to reply if anything is wrong here!): @editorconfig/developers 

     https://github.com/editorconfig/editorconfig/wiki/Board-Member

Please comment!

**Comment by florianb** [comment]
I really appreciate this evolvement. And i really hope that additional work of enforcing the board rules isn't getting in the way of this organizational feature.

However, if this gets widely accepted i'd like to open a application.

**Comment by xuhdev** [comment]
@florianb The organization feature is to ensure that people who can get automatically approved are already a non-trivial contributor to the project. I agree that it is some sort of security hole. I'll think about it.

**Comment by xuhdev** [comment]
@florianb I reformulated the rules. Please comment again. At this point, I guess we should give one week time to form a base board with at least a few people to evaluate new membership applications. Sorry.

**Comment by johan** [comment]
Nice! I suspect we'd minimize come/go noise if instead of requiring 50% majority of board members, and filtering out inactives, require a 50% majority among board votes, and don't gc members vigorously.

If a small always active board is a primary goal, though, keep things as is. I don't know if my experience on open source projects is typical, but having not heavily engaged elders around can be helpful when new, vigorous, but polarized people show up and try to wrest their will.

Editorconfig isn't a super hot target for that kind of people, I suspect, but I figured I'd share the thought, anyway.

**Comment by johan** [comment]
I e: ignoring non-voting silent board members in vote counts, but having them around already for checks and balances if/when the charter is exploited, to weigh in, as needed.

**Comment by ffes** [comment]
Just a short note on the "picking up of EditorConfig"

Visual Studio 2017 will have builtin support for EditorConfig!
https://channel9.msdn.com/Shows/C9-GoingNative/GoingNative-54-Whats-New-In-Visual-Studio-2017-RC-and-Introduction-To-Vcpkg
From around 11:45, not much details though.

So the documenting and looking after the EditorConfig file format is likely becoming more important.

**Comment by sindresorhus** [comment]
I'm all for better formalizing the current rules, but I personally consider EditorConfig done. We've covered all the important things. The rest is better left to language specific linters. I don't intend on supporting any more rules in the Sublime or Atom plugin.

**Comment by xuhdev** [comment]
@treyhunner  @johan @ffes @sindresorhus Would you mind adding yourself to the list?

**Comment by ffes** [comment]
> Would you mind adding yourself to the list?

done

**Comment by xuhdev** [comment]
We have 4 members signed up now, which should be good for a start. I'll formalize everything. It's never late to add yourself in if you are eligible.

**Comment by Mpdreamz** [comment]
Just took the liberty to add myself too :smile: 

Another issue now that more tooling are picking up editorconfig files is namespacing of domain specific properties see e.g:

https://github.com/dotnet/roslyn/issues/15785

**Comment by treyhunner** [comment]
Added myself

**Comment by johan** [comment]
Sure; added.

**Comment by xuhdev** [comment]
OK, this issue should be closed now. I've added one more obligation: any changes to the rules must be approved by over half of the members. In the future then, we should now have rules to follow to make any major non-coding changes I can think of.
