### ISSUE TITLE
Use `off` as the standard value to turn off any option if applicable.

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#285]
See also #282 .

Let's decide it before Dec 28 GMT -12 23:59....

@editorconfig/board-member

**Comment by Mpdreamz** [comment]
Agreed.

Should we explicitly document the fact there is nothing special about `off` or would that be another thing vote worthy?

If we ever do need a breaking change ice be +1 on removing the leniency all together but that's for another day :)

**Comment by xuhdev** [comment]
This is a voting thread. Perhaps we should create a label for that...

**Comment by florianb** [comment]
I think the *rule* should be as short and on the point as possible. The explanation may contain that every value which is not otherwise defined is treated as invalid but in future evolvement only `off` is considered as being reserved and therefore may *never* be a valid value.

**Comment by Mpdreamz** [comment]
Created a `voting only` label, you are right @xuhdev discussion should be contained to the linked ticket only.

**Comment by jedmao** [comment]
Voting :+1:

**Comment by xuhdev** [comment]
Voting 👍

**Comment by johan** [comment]
I find both this proposal and #282 _way_ under-defined. We support less than ten properties. It is not unreasonable to flush out a full spec with the details of what it means for each property, with perfect clarity.

I _think_ this proposal is about the situation where you have more than one `.editorconfig` file that applies in a directory structure, such as when `foo/bar/.editorconfig` lacks a `root: true`, and `foo/.editorconfig` has `root:true`, to let the former unset properties from the latter in the cascade of editorconfig files that apply settings for files below `foo/bar/`, without asserting a new preference – i e, setting that property back to whatever user or editor defaults assign. But I am not sure.

If it is, I think `off` is a bad name that sounds like a duplicate of `false` but actually means something like `default` or `unset` (two maybe better names).

Here are the properties and their documented current set of legal values:

# Supported by all

### `indent_style`: [`tab`, `space`]
### `indent_size`: [`tab`, _positive integer_]
### `tab_width`: [_positive integer_]
### `end_of_line`: [`lf`, `crlf`, `cr`]
### `charset`: [`latin1`, `utf-8`, `utf-16be`, `utf-16le`]
### `trim_trailing_whitespace`: [`true`, `false`]
### `insert_final_newline`: [`true`, `false`]
### `root`: [`true`]

# Supported by some

### `max_line_length`: [_positive integer_, `off`]

If we are to have voting on issues that are spec changes, at least I would prefer them to be in the shape of pull requests, proposing the change to the standard itself, so we all have perfect clarity about what we are voting on, and can come with input about what needs cleaning up or clarifying.

While I know we can edit and improve existing issue descriptions, I vote for closure of this issue and a do-over, so we don't end up with a new description that is good, but predates a few of the votes, which may no longer reflect those voters' opinion on the rewritten spec, if it turns out they voted on a different understanding of the proposal.

**Comment by jedmao** [comment]
All good points, @johan. `off` does sound like it could be confused with `false`. The issue is that it's already a suggested value for `max_line_length`. **_Perhaps we should create a "list" of reserved values that we will never use, so that people can use whichever seems more appropriate for them?_**

## `default`
I really like `default`, as you've mentioned, because it makes it totally clear that we're getting the default value (whatever that value might be); however, people don't always know what the default value is and, in fact, **_not all rules have a default_**, which introduces even more confusion. I suppose if you knew the default value, you could just use THAT value to reset it, right?

## `unset`
I also like `unset`, because it tells me that even if I've had it set before, this is going to unset/override that setting with the default setting or, if the rule doesn't have a default setting, it just unsets the rule!

The caveat with introducing `unset` as a value, is that we would have to add BOTH `off` and `unset` as reserved values that we will never use in the future (i.e., reserved for unsetting rules).

## Conclusion
Now I feel like `unset` is a great idea, even though it introduces yet another reserved word (like `off`). In fact, we should probably change the documentation to tell people to start using `max_line_length = unset` if/when we decide to go this route.

Do we need another issue to specifically vote for `unset` or are there any strong objections here?

**Comment by jedmao** [comment]
I'm rescinding my 👍 on this thread for the reasons stated above.

**Comment by florianb** [comment]
I completely agree to @johan & @jedmao. And having thought a little bit about it, i think replacing `max_line_length`'s `off` by 'unset' would be a non-breaking change, wouldn't it?

I would really like if we could discuss changes and vote in a PR - that would enable us to talk about the landing changes.

So if this rule is being voted on i would be 👍 , but i would prefer it replaces the off-value of max_line_length, too.

**Comment by xuhdev** [comment]
@florianb We can make `max_line_length` a special case, which shouldn't cause any problems.

I think this thread has actually become a discussing thread, so I removed the "voting only" label. I'll recreate a voting only thread with `unset` replacing `off`. Agreed? Discussion shall continue here.

**Comment by florianb** [comment]
If this causes no troubles i would propose to drop `off` in long term. It would just not be necessary carrying this on.

If editorconfig would be semver'ed i would mark `off` as becoming deprecated in the next major release, which in fact would mean removing it from the documentation (old editoroconfig's should still not be affected by that change). The standard would be more condensed if the unset-rule is unique.

**Comment by xuhdev** [comment]
@florianb If I understand it correctly, that's a different proposal to `max_line_length` specifically, right? If we pass this universal unset option, we can put that on the agenda.

**Comment by florianb** [comment]
@xuhdev - i didn't think that way round, but yeah - you're right!

Oh and one question, what is the voting about, is it just about if there is the intention to introduce `unset` or is it also about how? Because if it is the latter it would be nice to have some kind of an example how it will look like in the end.

**Comment by johan** [comment]
Example request seconded. :)

(On the meta side, this may be the last thing I am weighing in on as a "board" member, as I'm signing on with a "no non-work comp.sci engagements" employer in a bit. Still a fan of the project, even if I'll have to go more incognito, role-wise.)

**Comment by jedmao** [comment]
I think `unset` would definitely be a global value and it's not just about multiple `.editorconfig` files in a single project. It could even be in the same root file, e.g.:

```ini
root = true;

[*]
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true

[*.md]
indent_style = unset
indent_size = unset
```

You could also use it for nested `.editorconfig` files to achieve the same purpose, but it would look exactly the same.

@florianb, @johan, is this the example you were requesting or are you asking about something else?

**Comment by jedmao** [comment]
I should add that "supporting" this universal `unset` value requires no development updates at all, only documentation updates, as the feature already works this way and has for quite some time. We're only reserving `unset` so that there is confidence it shall not be used in the future for something else. Just to make sure everyone is clear.

**Comment by johan** [comment]
Good example! I forgot there's an in-file cascade too, with respect to different overlapping globs. I assume my multi-file example is correct, too?

**Comment by jedmao** [comment]
Yes, @johan, your multi-file example is also correct.

**Comment by xuhdev** [comment]
@jedmao Thank you! I've updated the voting thread #287 with an example accordingly.

**Comment by florianb** [comment]
Yeah @jedmao - that's exactly what i was after.

:bulb: It might also be a good idea to add the headline and the explanation (@jedmao's description should pretty much do it) along with the example, so we would be able to see & discuss what will happen to the properties-description in the wiki?

Like this:

## Reserved Values
### `unset` - disables treatment of Property by editorconfig

The `unset`-keyword can be used to explicitly disable editorconfig's treatment for the given property. It is reserved so that there is confidence it shall not be used in the future for something else.

```ini
root = true;

[*]
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true

[*.md]
indent_style = unset
indent_size = unset
```

**Comment by xuhdev** [comment]
Updated, thanks.

**Comment by sindresorhus** [comment]
I'm 👍 on the `unset` proposal.

**Comment by xuhdev** [comment]
@sindresorhus @jedmao Can you do a formal vote by commenting in #287 ?

**Comment by jedmao** [comment]
@xuhdev #287 already has my 👍 on the original message. It's just not a separate comment.

**Comment by xuhdev** [comment]
@jedmao Can you make an actual comments? Since that 👍 is just too easy to be changed and leaves no record. We probably should use a dedicated voting system in the future.

**Comment by leandro-lucarella-sociomantic** [comment]
Will this also work to *unlink* `indent_size` and `tab_width`. I want to configure `indent_size` for my projects, but I don't want this to mess with user configuration for `tab_width`.

So I would like to be able to do:
```ini
indent_size = 4
indent_style = space
tab_width = unset
```

**Comment by jedmao** [comment]
If you don't want it to mess with `tab_width` then dont re-set `tab_width`. Problem solved. Just do:
```ini
indent_size = 4
indent_style = space
```

**Comment by leandro-lucarella-sociomantic** [comment]
> If you don't want it to mess with tab_width then dont re-set tab_width. Problem solved. Just do:
> 
> indent_size = 4
> indent_style = space

Well, the problem is plugins are actually following the specs:

> tab_width: a whole number defining the number of columns used to represent a tab character. This defaults to the value of indent_size and doesn't usually need to be specified.

Go figure :wink:

**Comment by jedmao** [comment]
@leandro-lucarella-sociomantic that's a bit of a weird scenario, but in that case what you suggested in the first place would work just fine. In fact, it should already work today, so you can go ahead and try it.

**Comment by xuhdev** [comment]
@leandro-lucarella-sociomantic It should work like `tab_width` is never specified. Probably we should just clarify it better.

@sindresorhus I'll take your 👍 here as your vote.

**Comment by leandro-lucarella-sociomantic** [comment]
> @leandro-lucarella-sociomantic that's a bit of a weird scenario

Is not at all, I want tabs to remain whatever it was configured by the user in their editor when the project use X spaces for indent. Why touching the tab config at all?

> but in that case what you suggested in the first place would work just fine. In fact, it should already work today, so you can go ahead and try it.

`unset` should already work in all plugins? Because in the past someone told me to use `none` and I think it did for a while but it stopped working.

**Comment by leandro-lucarella-sociomantic** [comment]
I just tried in VIM, and is not working with `unset`.

**Comment by jedmao** [comment]
Try running an EditorConfig CLI tool on the file in question to see if the core at least works and produces the expected configuration. If not, file an issue with core. If it works however, file the issue with the VIM plugin. Also, you could try another editor for a sanity check, but it should definitely work today, none or unset or anything that's not a supported value.

**Comment by jedmao** [comment]
`npm install editorconfig -g` if you're using `npm`. Otherwise, there is a C core you could use. Once installed, you just run `editorconfig foo.js` for example and it'll tell you what configuration applies to that file. Please file a separate issue to continue this discussion.

**Comment by xuhdev** [comment]
Updated the wiki now.
