### ISSUE TITLE
could you standardize the format command?

### ISSUE THREAD

**Issue by zzzgit** [editorconfig/editorconfig#296]
when we run the build-in command `format`,the result will be different from each other editors.
[this page](https://code.visualstudio.com/Docs/languages/javascript#_formatting) have listed some rules of the `format` command.
could you standardize the behavior of `format` command by adding these rules to `.editorconfig`

**Comment by xuhdev** [comment]
What does the "built-in command `format`" refer to?

**Comment by jedmao** [comment]
@xuhdev he's talking about an editor's ability to format a block of code (make it all pretty).

@zzzgit, formatting code is a language-specific concern and has no place in EditorConfig, because it's language agnostic. That said, you can add whatever additional properties you want to your `.editorconfig` file and it will work, so long as there is an editor extension that understands those rules.
