### ISSUE TITLE
Why is utf-8-bom discouraged?

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig#297]
On the [supported properties](http://editorconfig.org/#supported-properties) section of the front page, it states the following about `utf-8-bom`:

> charset: set to latin1, utf-8, utf-8-bom, utf-16be or utf-16le to control the character set. Use of utf-8-bom is discouraged.

My question is why? Why are we discouraging the use of `utf-8-bom`? I feel like EditorConfig should be pretty agnostic about these types of things and `utf-8-bom` is very prevalent in Visual Studio projects.

@treyhunner, do you have any background or context about the inclusion of this? Maybe @xuhdev?

**Comment by robsonsobral** [comment]
BOM can cause issues on web development. Is there an advantage in using it on Visual Studio projects?

**Comment by jedmao** [comment]
@robsonsobral there are plenty of projects that have nothing to do with web development; thus, it's a bit strange that we would make a blanket statement that `utf-8-bom` is discouraged. The BOM signature is useful in immediately determining the charset for a document is `utf-8` w/o doing anything tricky. Conceptually, I think it's a good idea. Yes, it does have issues in some modern applications, but a lot of that can be alleviated (e.g., by default, gulp strips BOMs).

The advantage is that w/o a BOM you have to do a certain amount of guess work to determine what charset a doc uses. With the BOM, there's no guess work at all. You know for sure that you're dealing w/ the charset you've detected.

**Comment by xuhdev** [comment]
The reason is [here](https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom/2223926#2223926).

The discussion about it on EditorConfig was [here](https://groups.google.com/forum/#!searchin/editorconfig/bom|sort:relevance/editorconfig/oAqqIFHeWyo/h_Lej23zzO4J).

**Comment by jedmao** [comment]
It sounds to me like it's fair to discourage its use in web development projects, but not necessarily other contexts. I dunno.

**Comment by xuhdev** [comment]
Thanks for the reporting. Unfortunately it's what the Unicode specification recommends.

I've added a link on the homepage to explain the reason editorconfig/editorconfig.github.com@233d8b2cd15db22be494e9e7e11d8bcd4295ad1c

**Comment by jedmao** [comment]
Thanks, @xuhdev!

**Comment by binki** [comment]
On my web project it’s actually required. Without it, the Razor templating engine assumes my file is in the local charset and misreads `…` as mojibake.

**Comment by danm-de** [comment]
> Thanks for the reporting. Unfortunately it's what the Unicode specification recommends.

Those recommendations are not applicable in any context. See Unicode standard (page 36, 2.6 2.6 Encoding Schemes):

[...] _Use of a BOM is neither required nor recommended for UTF-8, but may
be encountered in contexts where UTF-8 data is converted from other encoding forms that
use a BOM **or where the BOM is used as a UTF-8 signature**.  See the “Byte Order Mark”
subsection in Section 16.8, Specials, for more information._ [...]

Lets have a look at page 550 (16.8 Specials):

[...] _2. Unmarked Character Set. In some circumstances, **the character set information
for a stream of coded characters (such as a file) is not available**. The only information available is that the stream contains text, but the precise character set is not known. **In these** two **cases, the character U+FEFF is used as a signature to indicate the byte order and the character set by using the byte serializations** described in Section 3.10, Unicode Encoding Schemes._ [...]

> I've added a link on the homepage to explain the reason [editorconfig/editorconfig.github.com@233d8b2](https://github.com/editorconfig/editorconfig.github.com/commit/233d8b2cd15db22be494e9e7e11d8bcd4295ad1c)

The author just answers a question: **What's different between UTF-8 and UTF-8 without a BOM? Which is better?**
It is not a wrong answer - it is just the wrong advice for our problem. I am working with Visual Studio on Windows and are having serious issues caused by wrong character set detection. 

Since we added this line in our .editorconfig:

```
[*.{cs,sql,config,csx,fsx}]
charset = utf-8-bom
```
a lot of these issues disappeared.

**Comment by danm-de** [comment]
> BOM can cause issues on web development. Is there an advantage in using it on Visual Studio projects?

Yes, definitely if you are working in a heterogeneous team. Visual Studio uses the user's current culture when storing files. (Windows-1252 in Germany, Windows-1251 in Russia, Windows-1255 in Israel ...)

**Comment by perennialmind** [comment]
> Yes, definitely if you are working in a heterogeneous team. Visual Studio uses the user's current culture when storing files. (Windows-1252 in Germany, Windows-1251 in Russia, Windows-1255 in Israel ...)

The only way to move from the legacy ANSI quagmire that nobody wants and we're all stuck with would be for Microsoft to un-deprecate it and recast the ANSI/Unicode distinction as 8-bit/16-bit coding unit and make it possible to advertise UTF-8 as a default. Thankfully, [that's what they're doing](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page). 
It is now *possible* to opt in to the UTF-8 codepage for system locales. It's still behind a BETA flag, so as not to expose [broken software](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page) as such.

It's a small thing, but using Visual Studio with GetACP() == CP_UTF8 was like shaking out the grit from my boots after an overlong walk.

**Comment by deadmann** [comment]
previously I create a file in rider, and when my page loaded, I see lot of unreadable character, that was because the BOM header was missing in our RTL language (Persian Aka Farsi or Parsi). The only thing could fix it was to add BOM, and saying it is deprecate. is somehow rude when there is no alternative.

**Comment by binki** [comment]
@deadmann How is your “page” being loaded? If it is sent over HTTP, the [`Content-Type` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#syntax) can be used to specify the encoding. This prevents the client from guessing the wrong charset. This regards how your program creates output, not how the source files are managed. You may need to configure your buildsystem.

Setting `utf-8` in `.editorconfig` allows you inform all text editors that the source files in your project should be treated as UTF-8 instead of guessing. If the editors are allowed to guess, they may try to use ’90s-era techniques such as your system’s current locale/codepage to guess the encoding of files. This is because they are trying to avoid breaking behavior changes, but as a result new projects today are still being created using codepages rather than UTF-8. Thus the `.editorconfig` boilerplate is necessary to move beyond that…
