### ISSUE TITLE
EditorConfig not working at all

### ISSUE THREAD

**Issue by kevonh** [editorconfig/editorconfig#312]
I am on the latest update of VS 2017.  
I installed the plugin from [Mads ](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig).  
I added a .editorconfig file in the root of the solution
I added one setting:

root = true
[*.cs]
csharp_style_inlined_variable_declaration = true:error

I added some code which violated this rule.  Then I built, and expected to get an error.  Nothing happened.

What am I doing wrong???

**Comment by florianb** [comment]
Hi @kevonh,

thank you for getting in touch. Your issue is about an extra feature of Mads Kristensen's plugin which is not covered by the editorconfig-standard as it is defined by [editorconfig.org](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties).

You should close this issue and [open a new issue in Mads's repository](https://github.com/madskristensen/EditorConfigLanguage/issues/new) to get help.

**Comment by kevonh** [comment]
My issue is about editorconfig file not impacting Visual Studio.  I was providing all of my system details for reference purpose. 

My issue remains that any .editorconfig file in Visual Studio does nothing.  How it got there is not important.

**Comment by florianb** [comment]
Okay - sorry for that confusion. But that issue still belongs to Mad's implementation of this standard and is plugin-specific. This repository is for more general issues with the format in general.
