### ISSUE TITLE
equivalent of vim's spell and spelllang settings

### ISSUE THREAD

**Issue by mcepl** [editorconfig/editorconfig#315]
Following discussion on https://github.com/vim/vim/issues/1015 I returned to ``editorconfig`` idea whether it could be helpful to me. I am Czech and programmer by profession. Which means that I have a huge variety of projects with both languages. Most of my ``.vimrc`` files are just:
```viml
set spell
set spelllang=cs
```
(or ``spelllang=en-gb``). That just switches on spelling for documents in given directory and sets the spelling language to Czech (or UK English).

I look at #293, but I agree, that it is too specific and exception files are hard to be done in the editor independent manner. However, the two lines I use are a way more manageable. Couldn't editorconfig plugins start to support at least these two, please?

**Comment by mcepl** [comment]
Mock implementation of this idea is in the pull request above.

**Comment by mcepl** [comment]
And there is now also separate project as a plugin for editorconfig-vim in https://github.com/mcepl/editorconfig-vim-spell

**Comment by ppalaga** [comment]
If this is a proposal to improve editorconfig in some way, please be specific about what should be changed and why in editorconfig (you speak of Vim rather than editorconfig). Please make your proposal understandable without the need to follow the links. Ideally reword the initial post so that the people do not need to parse five irrelevant posts to figure out what you propose.

**Comment by mcepl** [comment]
I propose to add two new configuration values ``spell_langugage`` and ``spell_enabled``.

* ``spell_enabled`` could have values ``true`` and ``false`` (or 
actually, anything else).

* ``spell_langugage`` have a string value of ISO 639-1 language 
code possibly with the dialect extension (e.g., ``cs`` or ``en_GB``).

Therefore it is possible to have ``.editorconfig`` like:
```ini
[*.rst]
spell_enabled = true
spell_language = cs
max_line_length = 65
```
It is possible that ``spell_enabled`` option is unnecessary (and that ``spell_enabled`` == ``false`` is just an equivalent of unset ``spell_language``, but having this options feels more obvious and easier to maintain).

**Comment by xuhdev** [comment]
@mcepl I personally think this is actually a viable new feature (may need a bit adaptation). Can you propose it in https://github.com/editorconfig/editorconfig/issues ? When we decide to support a new property, normally we will do it integrally, not just in one editor.

**Comment by mcepl** [comment]
@xuhdev Ehm, and where do you think we are?

**Comment by ffes** [comment]
I would not vote against this, but know that the editors I use most (Notepad++, Visual Studio and vscode) need a plugin to get this done. And I don't know if those plugins are configurable through an api.

**Comment by mcepl** [comment]
> I would not vote against this, but know that the editors I use most (Notepad++, Visual Studio and vscode) need a plugin to get this done. And I don't know if those plugins are configurable through an api.

I don't understand. Of course, these editors' plugins miss on the implementation of the standard which has not been agreed upon yet. I would expect, if accepted and there was demand from their users, they would eventually add the functionality.

**Comment by mcepl** [comment]
> Yes, that is most likely how it will go. I just wanted to point out that many well known editors don't have a built-in spell checker and that can take quite some time before a new property is implemented once accepted.

Ahh, I see. Yeah, I am a Linux guy, so (although we have our own problems https://github.com/neovim/neovim/issues/356) somehow all editors have some kind of spell checker, so I missed on that.

> But I do think the properties you suggest are very useful. And being Dutch I feel the same pain about switching languages all the time.

Preach it, brother, preach it! (I am a Czech writing a lot of stuff in en_GB ;)).

> Therefore we need to specify how we expect the editors to react to the new properties.
> 
> ```ini
> spell_enabled = true
> ```
> 
> That would enable the spell check, so I would think that would mean that the red curls should be shown underneath a misspelled word. And when not set or false that feature should be disabled. Am I correct?

Yes, you are (red curl line, or whatever means the editor decides to mark misspelled words).

> 
> In #293 @jedmao [suggests](https://github.com/editorconfig/editorconfig/issues/293#issuecomment-271926372) to use `locale = en-us` to set the language and your suggestion is to use `spell_language = en_US`. We need to decide which property to add and how the language from ISO is spelled (underscore vs dash, all lower vs dialect in upper case).

I would say that the value could be case insensitive (editor will have to do some translation to its local codes anyway, and I don't think there is ever language code which would differ just in capitalisation).

Hmm, concerning hyphen v. underscore, I think I had it wrong. https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry seems to be based on language-DIALECT (e.g., en-GB), but again I would prefer it there was some standard way (e.g., following this IANA register), but it would be very permissive in accepting en_gb and en_GB as well.

> I like `locale`. It can be used broader then just `spell_language`.

Which makes a good reason, why we should stay with ``spell_langauge``. ``locale`` could mean to many things at once (format of paper, time, data, currency, etc.).

> But I like `en_US` better. EditorConfig already uses underscores in the names of the properties.

You are right, we should definitively accept both.

**Comment by Carpetsmoker** [comment]
It seems to me that `spell_enabled` is a personal setting, like "auto indent", "insert closing parens", "display width of editor", etc. Personally, I wouldn't be too happy if my editor/IDE started enabling spell checking errors on random documents just because the editorconfig said so.

This is different from `spell_language`, which describes how the document is formatted, which is what EditorConfig is intended for (not enforce display settings like highlighting allegedly misspelled words).

`locale`, as proposed before, seems to make more sense to me. The Editor/IDE is then free to interpret that in a way that makes sense, which *could* affect spell checking, but could also affect e.g. number formatting, sorting, other stuff.

**Comment by mcepl** [comment]
There is now https://github.com/mcepl/editorconfig-vim-spell which can serve as a reference implementation.

**Comment by mcepl** [comment]
> It seems to me that `spell_enabled` is a personal setting, like "auto indent", "insert closing parens", "display width of editor", etc. Personally, I wouldn't be too happy if my editor/IDE started enabling spell checking errors on random documents just because the editorconfig said so.

You are right, so I withdraw ``spell_enabled`` property from the proposal and we are talking about ``spell_language`` property only. My implementation has been adjusted accordingly.

Concerning ``spell_language`` v. ``locale``: I would need a little bit more persuasion for that. Anybody else any opinion?

**Comment by gustaphe** [comment]
`language` is also a bit ambiguous. When editing a TeX file, for instance, the language is arguably both TeX and `en_gb`.

**Comment by gustaphe** [comment]
> The locale language is en_gb. The programming language is TeX. Two very different things.


Yes, and both of those could reasonably be called the file's `language`. That's my point. Calling it `spell_language` or `locale_language` disambiguates this.

**Comment by alerque** [comment]
Fully in agreement with the outcome of this discussion:

* Whether or not spell check is enabled is very much a user preference thing.
* Setting the locale for spell checking is something that the project can specify per file.
* EditorConfig should gain some standardized key for this value, probably in CLDR locale format.
* Yes this is different than the language of the file (e.g. in VIM `filetype` vs `spelllang`)
* Yes this is also different than setting a locale that could potentially change more than spell checking (such as date formatting).
* I don't care whether it is `spell_language` or `locale_language`, but call it something.

**Comment by arroselli** [comment]
> Following discussion on https://github.com/vim/vim/issues/1015 I returned to ``editorconfig`` idea whether it could be helpful to me. I am Czech and programmer by profession. Which means that I have a huge variety of projects with both languages. Most of my ``.vimrc`` files are just:
> ```viml
> set spell
> set spelllang=cs
> ```
> (or ``spelllang=en-gb``). That just switches on spelling for documents in given directory and sets the spelling language to Czech (or UK English).
> 
> I look at #293, but I agree, that it is too specific and exception files are hard to be done in the editor independent manner. However, the two lines I use are a way more manageable. Couldn't editorconfig plugins start to support at least these two, please?

**Comment by seifferth** [comment]
Just to add my own two cents as a plugin maintainer:

@alerque: Thanks for bringing the issue up again. I believe your summary really gets the point. I would very much like to see that incorporated into the editorconfig standard. Concerning the name for the variable: I called it `spell_language` in the [vis-editorconfig](https://github.com/seifferth/vis-editorconfig) plugin (see also https://github.com/seifferth/vis-editorconfig/pull/8). It looks like the maintainer of [vim-editorconfig](https://github.com/sgur/vim-editorconfig) made the same choice. I guess that makes `spell_language` the de-facto standard used by early adopters, so we might just want to stick with that.

@arroselli: As @alerque mentioned, `set spell` is pretty much a personal preference, not a project-specific or file-specific choice; hence it is probably most appropriate to specify it in your global `.vimrc`. Depending on which editorconfig plugin you use, you may already be able to specify the second setting, though. Maybe just try setting `spell_language` and see if that works.

**Comment by mcepl** [comment]
> @alerque: Thanks for bringing the issue up again. I believe your summary really gets the point. I would very much like to see that incorporated into the editorconfig standard. Concerning the name for the variable: I called it `spell_language` in the [vis-editorconfig](https://github.com/seifferth/vis-editorconfig) plugin (see also [seifferth/vis-editorconfig#8](https://github.com/seifferth/vis-editorconfig/pull/8)). It looks like the maintainer of [vim-editorconfig](https://github.com/sgur/vim-editorconfig) made the same choice. I guess that makes `spell_language` the de-facto standard used by early adopters, so we might just want to stick with that.

Ehm, author of [that change in vis-editorconfig](https://github.com/sgur/vim-editorconfig/pull/19) was the author of this proposal ;).

**Comment by seifferth** [comment]
Hi @mcepl,

I'm sorry if my earlier comment may have sounded like me trying to take credit for your work. I just wanted to point out that this proposal has already been implemented in two independent editorconfig plugins. I believe that this might be interesting to keep in mind when discussing the usefulness of the setting as it shows that there are people who want to see this; at least you and those who accepted your merge requests. Credits for getting the setting into those two plugins go to you, of course! (Also, I may have missed other plugins, so feel free to extend the list.)


Best

Frank

**Comment by mcepl** [comment]
> I'm sorry if my earlier comment may have sounded like me trying to take credit for your work.

Of course, I haven’t undestood it in that way. I was just amused.

**Comment by arroselli** [comment]
Altomare Anna

Caleb Maclennan ***@***.***> ezt írta (időpont: 2022. szept.
14., Sze 18:56):

**Comment by tovrstra** [comment]
Regarding the prefix (`spell`, `locale`, ...): I agree that the scope of the term `locale` is too broad. For example, some conventions related to `locale` are already fixed by the programming language (point versus comma). Also, when writing in other languages than English, I often still use the dot for a decimal separator.

It may be worth keeping in mind that the same setting may in future also affect grammar or types of checks related to the natural language. Maybe `natural_language` is a more future-proof name?

**Comment by cxw42** [comment]
Draft specification change: https://github.com/editorconfig/specification/pull/41

**Comment by alerque** [comment]
I agree with Matěj here, none of the other suggestions I've seen here have any advantages over `spell_language`. Most of them have specific disadvantages mentioned in discussion already.

**Comment by tovrstra** [comment]
I'm also fine with `spell_language`, with the understanding that it could be used beyond the strict scope of spell checking.

Note that grammar checking is already in Pycharm, based on languagetool. This is still rule-based, but can be called AI with a stretch. I think this is why Pycharm uses the term "natural language" instead of "spelling language", but I don't think anyone really cares about the difference. No one will ever seriously use different languages to check spelling and grammar.

**Comment by seifferth** [comment]
Natural Language is actually an established term in fields like
Computational Linguistics where you usually differentiate *natural* from
*formal* languages. "Natural Language Processing" describes processing a
language like English, Spanish, French, German, ... using some computer
program. This is different from writing a parser for python or xml,
which is also a form of language processing, but notably not called
*natural* language processing. (Natural languages usually complicate
things because they contain ambiguities that formal languages do not
contain. Formal grammars for natural languages, for instance, are usually
non-deterministic, so parsers for natural languages would often return
sets of possible interpretations.)

That being said, I do believe that `spell_language` is totally fine and
probably more easily understood by the average programmer. I also like
the idea of calling the setting `spelling_language` instead, which is
notably different from `spellchecking_language`. `spelling_language`
might also be more in line with editorconfig's preference for using long
names instead of abbreviations.

I believe that both `spell_language` and `spelling_language` could
reasonably be used for related features like grammar checks. Whatever
the outcome of this discussion will be, I'll be happy to adjust the
[vis-editorconfig plugin] accordingly.

[vis-editorconfig plugin]: https://github.com/seifferth/vis-editorconfig


On a different note: Should we include rules for how to specify multiple
languages? Doing something like span- or block-wise language annotations
is clearly out of scope; but allowing the use of a comma-separated
list of one or more language codes might be feasible. Spellcheckers
like hunspell(1) already allow to do this and I sometimes use that
feature. How spellcheckers handle multi-language spellchecking would be
up to the spellchecker developers. The easiest option could be to just
do a set union of the words that are known to be correct.

We might also want to designate the first language as the "primary" one.
I believe pandoc does something similar when converting to latex. If
we had a primary language, minimalistic plugin developers could even
opt out of implementing multi-language spellchecking and ignore all but
the first language code, while more ambitious plugin developers could
possibly use some probabilistic approach to detect which of the languages
each sentence of the text is written in. Users would then just choose
the spellchecker that provides the kind of experience that suits them
(the ultimate responsibility for getting the spelling right always lies
with the author anyway, not with the spellchecker).

**Comment by mcepl** [comment]
> On a different note: Should we include rules for how to specify multiple languages? Doing something like span- or block-wise language annotations is clearly out of scope; but allowing the use of a comma-separated list of one or more language codes might be feasible. Spellcheckers like hunspell(1) already allow to do this and I sometimes use that feature.

I would like that. Multi-language documents are quite common, and for example spellchecker in Firefox does exactly that: controls the union of all words for the selected languages.

**Comment by cxw42** [comment]
* +1 `spelling_language`
* One or multiple values is fine with me, but I slightly prefer specifying a  single spelling language per file.  That way the project lead can unambiguously say "please use exactly this natural language for your text".  I think that fits with the overall on-disk consistency goal of EditorConfig.

**Comment by mcepl** [comment]
> * +1 `spelling_language`
> 
>     * One or multiple values is fine with me, but I slightly prefer specifying a  single spelling language per file.  That way the project lead can unambiguously say "please use exactly this natural language for your text".  I think that fits with the overall on-disk consistency goal of EditorConfig.

Nothing stops you from doing exactly that, does it?

**Comment by alerque** [comment]
> That way the project lead can unambiguously say "please use exactly this natural language for your text".

You can do that anyway with a single value in an array. That's what all the values mean: please do it exactly this way for this project. But not all documents contain only one language. I compose documents that have three or four languages in the on a regular basis. There is no reason I shouldn't be able to tell my editor to "please check this set of files for spelling in English, Turkish, and Russian" for a set of files that contain multiple languages. Obviously if I wanted to constrain a set of files to a single language each that would still be an option.

**Comment by cxw42** [comment]
Fair point!   Since this is the first multi-valued property, I suggest we:
1. add the single-valued version
2. choose a list format we can use going forward for more than just this property
3. add multiple-value support to this property.

Please leave any comments you may have re. the single-valued version on proposed https://github.com/editorconfig/specification/pull/41!

**Comment by seifferth** [comment]
> Since this is the first multi-valued property, I suggest we:
> 1. add the single-valued version
> 2. choose a list format we can use going forward for more than just
>    this property
> 3. add multiple-value support to this property.

This does sound reasonable. Unfortunately, general purpose list formats
are not as easy as they might appear on first sight. The most simplistic
list format I can think of is the following one:

    <VAL><SEP><VAL><SEP><VAL>...

An example would be to use `[[:space:]]*,[[:space:]]*` as the separator,
which is basically what I suggested earlier. This way, we could just
write any of the following:

    spelling_language = en
    spelling_language = en,es
    spelling_language = en, es
    spelling_language = en      ,   es,     fr

Since adding a space after a comma is natural in most writing, allowing
whitespace around the comma (unlike in csv) should help preempt pointless
and annoying errors related to that.

Unfortunately, this very simplistic list format would break if `<SEP>`
should ever occur as part of any value. This is why general purpose list
formats such as csv or json contain slightly more involved quoting rules.
Since all valid singular values for the spelling_language property are
guaranteed to contain neither whitespace nor comma, choosing the more
simplistic list format seems safe enough in this case.

Reusing this format for any future property is also possible as long as
valid values for this unknown future property contain neither commas
nor leading or trailing whitespace (or whatever else we choose to use
as the `<SEP>` token). I feel that, in the case of editorconfig files,
this should be reasonable enough of an assumption, so I would propose
to not overengineer the spec at this point.

If we should ever introduce a multi-valued property with values that
are supposed to contain commas or surrounding whitespace, we can still
define some quoting rules that are applicable to that specfic property's
values. (In the case of leading or trailing whitespace we would already
need to do this anyway, because, if I am not entirely mistaken, whitespace
around the values is already being stripped.)

**Comment by alerque** [comment]
That would force us to accept *either* a single value or a list later or make everybody port their single values to a list of one. Either way sounds like a bum deal when we know now we need a list.

EditorConfig bears at least a passing resemblance to TOML. In this case the list syntax for TOML *and* YAML is basically the same. That's one option.

The other might be just have comma separated values.

**Comment by seifferth** [comment]
> That would force us to accept *either* a single value or a list later

True. Thanks for pointing that out. I didn't even think of this, since
in the simple list format I propose the singular value is the same as a
list with exactly one item. As noted, this is not necessarily the case
for all list formats. Therefore, allowing a single value now would rule
out any list format that is not backwards compatible with this single
value (or adding a terrible hack like "can be either a list or a value").
If we bake this backwards compatibilitiy issue into our choice of lists,
we might also just settle on the comma separated values right away.

**Comment by cxw42** [comment]
> general purpose list formats
are not as easy as they might appear on first sight

Exactly!  But if we pick a list format with respect to only one property and its requirements, we risk a very confusing situation in the future: different list syntaxes for different properties.  I think it would be less confusing --- and less effort --- to special-case this one property, if we had to, than to document and maintain multiple list syntaxes.

My #482 suggests migrating to actual TOML in part to support structured values unambiguously.

**Comment by ffes** [comment]
Know that dotnet already has some extensions with multiple entries and they use comma separated values

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036

**Comment by mcepl** [comment]
This discussion of multiple values is all nice and fun, but do we need to resolve it here in the ticket on `spelling_language` property? Currently, as I see it, editorconfig standard accepts only single value, but when multiple values are allowed, I see absolutely no problem with just switching this property to be a multi-value one. Please, use another ticket.

**Comment by cxw42** [comment]
Multi-language is now open as #619

**Comment by cxw42** [comment]
Proposal for multi-value syntax, in case anyone's interested --- https://github.com/editorconfig/editorconfig/issues/619#issuecomment-5383261122 .  Please respond over there if you have comments, not in this issue, to avoid confusion.  Thanks!
