### ISSUE TITLE
trim trailing semicolon

### ISSUE THREAD

**Issue by PascalSalesch** [editorconfig/editorconfig#331]
could the extension

trim_trailing_semicolon

be added?

**Comment by ffes** [comment]
Where would I ever want to use that for?

**Comment by iseriousnoob** [comment]
Some consider it a good habit to terminate each statement with a ;

However the JS standard (https://github.com/standard/standard) is specifying "No semicolons"

**Comment by ffes** [comment]
The link is interesting for https://github.com/editorconfig/editorconfig-defaults, I was unaware of that. I've opened an issue over there.

But **I** think such a setting is too language specific. Microsoft [introduced many C# settings](https://blogs.msdn.microsoft.com/dotnet/2016/12/15/code-style-configuration-in-the-vs2017-rc-update/) similar like the one you propose. But those are a Microsoft specific extension of the EditorConfig standard that only works in Visual Studio 2017 (AFAIK) and the entries are not considered an official EditorConfig standard.

**Comment by hgraeber** [comment]
This is function for which it's not important to set it project wide. Every developer may have his own preference about this.

**Comment by xuhdev** [comment]
@hgraeber Well, I disagree with that. Whether having a semicolon seems more like a project preference :)

**Comment by hgraeber** [comment]
@xuhdev It's not about having a semicolon or not. It's about removing them automatically. This is not the same like trimming blanks. The latter are entered by accident are often invisible and generate ugly diffs in version control. 

BTW, if we add the option trim_trailing_semicolon, do we want an option add_trailing_semicolon, that does the opposite for projects that want to have semicolons... (I am joking)

**Comment by iseriousnoob** [comment]
@hgraeber just like there is a add_trailing_spaces?

I don't think the editorconfig is about fixing accidentally typing letters. To quote editorconfig.org: "EditorConfig helps developers define and maintain consistent coding styles". As is I can not define the standard JS coding style in my editorconfig.

Additionally, semicolons are often entered out of habit. Removing them automatically conveys the coding style to the developer easily

**Comment by rm-code** [comment]
Btw this is useful for Lua as well. It also allows, but doesn't force you to use ';' which can lead to inconsistency across projects.

**Comment by florianb** [comment]
Touching semicolons effort semantic knowledge about the grammar, this task should - in my opinion - remain to static analysis tools.

See f.e.
- https://eslint.org/docs/rules/semi for JS
- https://github.com/FPtje/GLuaFixer rule `prettyprint_semicolons` for Lua

**Comment by osdm** [comment]
Can we open a separate github projects for domain-specific properties for each language? Aside from editors and IDEs, there are many linter and formatter tools that could use common format. Initially converters could be written for tools that won't support .editorconfig, so .jshintrc, .eslintrc.js, .clang-format, etc could be automatically created from .editorconfig, but maybe gradually direct .editorconfig support would appear in them.

**Comment by zur4ik** [comment]
2021 and +1 for this feature.

**Comment by pvinis** [comment]
this definitely feels like something that's not editorconfig's responsibility, as it depends on the language.

imagine there is a repo with no semis, and then you have semi=true. how is your editor supposed to know where to put semis? on an `if {` how is editorconfig going to know not to put a semi?

feels like this should be closed. this is not a general thing, it needs language awareness.

**Comment by xuhdev** [comment]
I agree. This is specifically about JS, not any other languages that I am aware of. Let's close this.

**Comment by ecarrizo2** [comment]
> this definitely feels like something that's not editorconfig's responsibility, as it depends on the language.
> 
> imagine there is a repo with no semis, and then you have semi=true. how is your editor supposed to know where to put semis? on an `if {` how is editorconfig going to know not to put a semi?
> 
> feels like this should be closed. this is not a general thing, it needs language awareness.

Most editor like PHPStorm allow you to decide if your semicolons are added or not, there are several languages that do not use semicolons. This is part of the Code Style on every IDE, Don't see why this is not a responsibility of the tool that people is using to "Override" those IDE configurations, by a standard file, mostly pushed to repositories so every person code in the same way.

even when the editorconfig already allows user to chose in which languages to apply the setting, so it end up being up to the users to use it or not.

If you don't like to add support for it, because of any reason, it does not mean that is not needed today, and that is not a responsibility of this tool (because it is exactly for those kind of things this tool is used), so I will prefer to understand better reasons to negotiate if the feature should be there or not, better than giving vague responses. 

In terms of priorities, yeah it may not be a really needed feature, but I Argue that the reasons for not implementing it that were given are wrong.

**Comment by kuohuanhuan** [comment]
Although the issue has been closed, I still want to express my opinion. I think it would be better to let linters i.e. ESLint or Prettier do this job.

**Comment by 80avin** [comment]
Sorry for commenting on a closed/wontfix issue, but I am unable to understand the editorconfig's stand.
My argument is above this particular issue.

From EditorConfig's homepage
>EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles

Any project will almost certainly have a language-specific configuration which will require doing changes in the editor, linter, beautifier, etc tools.
At the core, EditorConfig is a specification to `maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs`. Hence, it comes in the bucket of something like EditorConfig to generalize it.

EditorConfig doesn't have to implement support for these language-specific options in their own plugins, but just maintain a schema so that the tools/editors can have a single place to read the options from.

A close example of this is [pyproject.toml](https://packaging.python.org/en/latest/specifications/pyproject-toml/#arbitrary-tool-configuration-the-tool-table) which supports defining arbitrary tool configuration.

I propose EditorConfig also supports having a arbitrary language/tool-specific configuration which can act as a single place. It doesn't have to implement any functionality around these, but only schema.
Otherwise, it will end up becoming one more config file which you have to add to your project.

**Comment by cxw42** [comment]
@80avin #482 is a proposal for broader use cases, but certainly not the only possible future.

Re. @osdm's
> domain-specific properties for each language
that is being discussed in #404 and related issues.
