### ISSUE TITLE
Provide an editor config lint tool

### ISSUE THREAD

**Issue by AndyOGo** [editorconfig/editorconfig#340]
It would be nice to have an Editor Config lint tool, which could be run within the CLI or integrated into an Editor (as it is right now).

**Comment by florianb** [comment]
There are already linters out there: https://github.com/editorconfig-checker/editorconfig-checker.javascript

**Comment by AndyOGo** [comment]
@florianb 
Sorry my bad, I googled for lint editorconfig and couldn't find some usefull libs.

**Comment by florianb** [comment]
@AndyOGo - no worries. I have also seen a c-based linter but haven't used one of them yet. So it is probably still kind of experimental and your question points probably to the standard, where linters should be mentioned.

**Comment by xuhdev** [comment]
@editorconfig/developers Do you think we should have a wiki page listing these lint tools?

**Comment by mcandre** [comment]
editorconfig-checker is broken, insisting that content at the left margin (0 indentation) must be indented as a multiple of 4, or whichever column width was configured. Not much use.

**Comment by xuhdev** [comment]
@mcandre If it's broken, can you report in their issue trackers? They are run separately from main EditorConfig repositories.

**Comment by jedmao** [comment]
Also, there's ECLint.

**Comment by AndyOGo** [comment]
https://github.com/jedmao/eclint

**Comment by jedmao** [comment]
That's the one. I don't directly support it any more, but it's in good hands.

**Comment by mcandre** [comment]
eclint is okay, but in general the various editorconfig CLI apps are rather limited, neglecting to support recursive directory walks, and often falling behind the editorconfig standard. Would be nicer to have an official, always up to date tool.

Also, as much as I enjoy Node.js, I would prefer a statically compiled binary, so that I don’t have to add a complete programming stack to my non-Node.js projects. It gets hairy having to use Node, Python, Ruby, Bash, Haskell, GNU make, and the kitchen sink to lint my projects :/

**Comment by xuhdev** [comment]
@mcandre EditorConfig is developed quite distributedly. Unfortunately, due to lack of governance, even if we have an "official" linting tool, in terms of maintaining standard, it would be effectively no different from an "unofficial" one.

Regarding your second question, I agree with you that a single binary version often helps many users.

**Comment by ronkorving** [comment]
@mcandre It seems that unfortunately it's no longer being maintained. Open issues (valid bugs) not being responded to, vulnerable dependencies, last commit from 2018 (like this thread, I am aware :)). Just FYI, I'm not expecting you to do anything here.

**Comment by greut** [comment]
I've built one:
- https://gitlab.com/greut/eclint
- https://github.com/greut/eclint-action

Feedbacks appreciated.

**Comment by bcdady** [comment]
Since this thread is still open (and I found it fairly highly ranked in Google results, I'll add a nomination for running editorconfig-checker via mega-linter.
[editorconfig-checker#mega-linter](https://github.com/editorconfig-checker/editorconfig-checker#mega-linter)

There is a node.js and a docker dependency if you want to run the same mega-linter local runner as a preview to how mega-linter will check your project in CI/Actions, but once it's set up it's an effective solution to knowing that the linting in your CI pipeline will succeed, because you've already previewed, and perhaps resolved, any lint issues before pushing the latest commits.

**Comment by cxw42** [comment]
Possible duplicate of #103

**Comment by xuhdev** [comment]
> Possible duplicate of #103

I agree. Closing now.

**Comment by sanmai-NL** [comment]
@xuhdev You haven't closed this though,

**Comment by xuhdev** [comment]
Good point, clicked the wrong button... Thanks!
