### ISSUE TITLE
Deprecate `max_line_length` in favor of `rulers`

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig#387]
## Problem
I had to [lock a conversation recently](https://github.com/editorconfig/editorconfig-vscode/issues/53), because of the [lack of clarity](https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines) behind the [`max_line_length`](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length) rule that's quite technically [not even a rule yet](https://editorconfig.org/). Considering the [years of controversy behind this rule](https://github.com/editorconfig/editorconfig/issues/89), I propose we deprecate it. But considering it's [not actually an official rule (yet)](https://github.com/editorconfig/editorconfig/wiki/Property-research:-maximum-line-length), I suppose "deprecate" is the wrong word to use. Abandon it? Prevent it?

Before suggesting an alternative, I have to briefly cover the reasons why this rule is particularly a problem:

## Implementation
Should it be implemented as [soft wrapping](#soft-wrapping), [hard wrapping](#hard-wrapping) or just a [ruler](#ruler)?

### Soft wrapping
Soft wrapping has no place in EditorConfig, because it is a user preference that has the potential to annoy half of the users that are forced to use it. There's nothing special about soft wrapping. It's not intended to prevent or enforce anything either.

### Hard wrapping
This would make more sense; however, it would also require EditorConfig be syntax aware in order not to cause code errors. As such, enforcing any kind of hard wrapping makes much more sense in a syntax-aware extension, such as a linter or formatter, as EditorConfig remains a syntax agnostic tool.

### Ruler
This has to be the least invasive solution to the problem. It still doesn't prevent anyone from breaking the rule, but it does indicate some level of intent; thus, might prevent some users from going past it? Vscode supports multiple rulers, so should it replace all of my rulers with just the one? Should it merge with my existing rulers? We need some clarity for plugin/extension authors if this is to be the solution.

## Solution
For the reasons stated above, I don't think EditorConfig should at all be responsible for soft- or hard-wrapping files. If we are to do anything at all, the least we can do is support a `rulers` rule that doesn't imply any sort of action or responsibility on EditorConfig's part, aside from simply displaying one (or more) rulers.

With all the controversy, this has to be the only way make people 😃 

### The pitch
```ini
rulers = 80, 100, 120
```
If specified, the `rulers` rule would replace any user-specified rulers with one (or more) rulers. EditorConfig **SHALL DO NOTHING ELSE**, period! Let me be absolutely clear. EditorConfig **SHALL NOT** be at all responsible for soft- or hard-wrapping. This does not prevent other extensions from using the EditorConfig core as a tool to do exactly that (however they may seem fit) but it remains **NOT** the responsibility of EditorConfig.

#### Limitations
If the editor in question does not support multiple rulers, the first ruler is used. Willing to hear some arguments to the contrary.

Simular issue: #89

**Comment by rdumont** [comment]
Hi, I'm the one who originally proposed editorconfig/editorconfig-vscode#53 for implementing the `max_line_length` property.

I must say that right after reading the first replies and then seeing the issue closed, I had closure myself 😄  All of the arguments against it make lots of sense, and I was really only thinking about Markdown when I first proposed it.

So now, about the `rulers` property, I don't think that it should be adopted either, since rulers are no more that visual cues, and I just love the simplicity of EditorConfig as it is.

**Comment by jedmao** [comment]
And if that's the outcome here, I'm totally fine with that!

**Comment by ulope** [comment]
The original `rulers` issue (#89) has 64 👍 votes and many, many comments. That should be a clear signal that there is definitely interest.

**Comment by andyearnshaw** [comment]
@jedmao thanks for starting this discussion. As you are already aware, I'm quite opinionated on this subject 😄. 

I have no argument against introducing `rulers`, but I don't think `max_line_length` should be deprecated. `rulers` does not convey the same semantic importance of "you may not go past this point" as `max_line_length`, which has absolutely no ambiguity. 

Personally, I don't think it matters that `max_line_length` needs an editor to be syntactically aware, because most editors already are syntax aware in some way (mainly for highlighting). The onus is on the editor or a plugin to support hard wrapping, and I think EditorConfig should continue providing that value as an indicator of where hard wrapping should occur.  Furthermore, it's immensely useful for productivity for an editor to know _where to break code_.

FWIW, I have developed code in Vim for over 5 years and never had an issue with the hard-wrapping in languages such as bash, config files, html, javascript, css, markdown, c/c++, java and python. However, I did have an issue with soft-wrapping, used by my colleagues, which made reading code and commits on the command line a nightmare. Rules like `max_line_length` encourage good practice, and more editors should strive to support it.

Hard wrapping has many benefits that make it worthwhile:

 - Produces more readable code
 - Keeps actual line breaks consistent through paragraphs of text
 - Easier to navigate through code that is hard-wrapped
 - Considerate of command line users, or users that use panels in the workspace to maximise productivity

> I had to [lock a conversation recently](https://github.com/editorconfig/editorconfig-vscode/issues/53), because of the [lack of clarity](https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines) behind the [`max_line_length`](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length) rule that's quite technically [not even a rule yet](https://editorconfig.org/).

I don't understand why it's 'quite technically not even a rule yet'. `max_line_length` is [listed here](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties), linked to from the EditorConfig website, referenced as the 'complete list of properties'. Despite the other reasons you gave in another thread, neither does anywhere suggest that it is not an official rule, and I don't see any lack of clarity. If it is not an official property, then it should be marked as such.

> Considering the [years of controversy behind this rule](https://github.com/editorconfig/editorconfig/issues/89), I propose we deprecate it.

I see no such controversy in that thread, could you provide more context?  There are a few arguments against, such as the syntax one you make, and one highly opinionated comment ('hard wrapping is archaic because editors support soft wrapping'), but no real controversy. Overall, the sentiment seemed to be in favour of `max_line_length`.

> As such, enforcing any kind of hard wrapping makes much more sense in a syntax-aware extension, such as a linter or formatter, as EditorConfig remains a syntax agnostic tool.

I'm repeating myself from the other thread here, but there aren't linters for all file types, and even for the ones that are, they're rarely enforced or even encouraged in dev environments. Projects can have many different file types, requiring teams to install and run linters for everything is not a practical way of telling them that they should limit their lines to a specific length.  Many style guides provide a maximum line length, but many linters do not have their "fix" feature executed until save, whereas hard wrapping can occur automatically as the threshold is crossed.

It may be worth softening the description of `max_line_length` to advise the editor to add a ruler at the value column if hard wrapping is not implemented, so that plugins that implement hard wrapping can still be automatically set up without _.editorconfig_ parsing being one of their concerns.

**Comment by jedmao** [comment]
> `rulers` does not convey the same semantic importance of "you may not go past this point" as `max_line_length`, which has absolutely no ambiguity.

I'm not arguing that `rulers` fulfills the need of `max_line_length`. I'm arguing that `max_line_length` should not be the responsibility of a syntax-unaware tool such as EditorConfig.

> I don't think it matters that `max_line_length` needs an editor to be syntactically aware, because most editors already are syntax aware in some way (mainly for highlighting). The onus is on the editor or a plugin to support hard wrapping, and I think EditorConfig should continue providing that value as an indicator of where hard wrapping should occur. Furthermore, it's immensely useful for productivity for an editor to know _where to break code_.

I'm a bit confused by this point, because your original post was within the context of vscode, which has none of this functionality you propose an editor should have. The only setting that's remotely close is `html.format.wrapLineLength`, which sets the "maximum amount of characters per line" for HTML files only. There doesn't appear to be any other line length settings within vscode, language-specific or otherwise.

VSCode does provide the ability to handle [document formatting](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#additional-language-server-features) within an extension, but this is much more complicated than EditorConfig should be and it gets into, again, the territory of EditorConfig being aware of language-specific needs. There remains to be no one setting that EditorConfig can leverage from vscode to achieve this goal in a graceful and simple way.

If this issue is important to you, I strongly suggest you start at the root of the problem. In this case, for you, that would be the [vscode issue tracker](https://github.com/Microsoft/vscode/issues). I would start by asking if they would consider the addition of a user/workspace setting that would somehow enforce max line length for any given language. From there, an EditorConfig extension would only have to leverage that setting instead of doing a bunch of super-complex manual logic, which EditorConfig should **NOT** be doing.

> Rules like `max_line_length` encourage good practice, and more editors should strive to support it. Hard wrapping has many benefits that make it worthwhile.

I'm not arguing that `max_line_length` is not valuable, so you don't have to try and sell me on this point. I only don't think it has a place in this project, because of the complexity attached to it and of the syntax awareness required for any such implementation.

> If it is not an official property, then it should be marked as such.

I think that's the very point this thread is trying to achieve here. I would like it marked as deprecated or removed entirely.

> I see no such controversy in that thread, could you provide more context?

I use the word controversy, because the issue started back in 2013 and still there has been no resolution. Nobody seems to agree on how it should be implemented.
 
> There aren't linters for all file types, and even for the ones that are, they're rarely enforced or even encouraged in dev environments.

The important part is that they "can be" enforced, if it's important enough to the team.

> Projects can have many different file types, requiring teams to install and run linters for everything is not a practical way of telling them that they should limit their lines to a specific length.

I would argue that line length limitations can change depending on file type, so this makes all the sense in the world to me, especially considering the alternative of breaking code by blindly breaking lines at a specified limit because of syntax unawareness.

> Many style guides provide a maximum line length.

If a rule can be enforced, then it has no need to be in a style guide. Style guides are for manual, human processes. In fact, in a perfect world, style guides shouldn't even exist, as linting, fixing and formatting should replace them all. In this way, developers can focus on important things instead of bikeshedding over trivial things.

> Many linters do not have their "fix" feature executed until save, whereas hard wrapping can occur automatically as the threshold is crossed.

A feature that vscode, e.g., still does not have. It seems as though you're expectation is that EditorConfig plugins/extensions should be responsible for tracking each keystroke and responding to them as they hit a specified limit. Do you realize how complex this becomes? EditorConfig is supposed to be a simple tool, leveraging editor features instead of writing custom implementations.
 
> It may be worth softening the description of `max_line_length` to advise the editor to add a ruler at the value column if hard wrapping is not implemented, so that plugins that implement hard wrapping can still be automatically set up without _.editorconfig_ parsing being one of their concerns.

This was one of my main points, that the `max_line_length` rule, if an official rule at all, requires more clarity for how extension authors should be implementing it. I would add that "adding a ruler" is a bit too simple of an instruction, however, as the user might already have any number of rulers already setup.

As for "plugins that implement hard wrapping" using the ruler as an indicator for hard wrapping? I think this is a horrible idea, because it makes too many assumptions about why the ruler is there in the first place. The most graceful way of handling this is for any such plugin to use the EditorConfig core library that matches the language of the plugin to determine where the hard wrapping should occur.

**Comment by andyearnshaw** [comment]
> I'm not arguing that `rulers` fulfills the need of `max_line_length`. I'm arguing that `max_line_length` should not be the responsibility of a syntax-unaware tool such as EditorConfig.

Your use of "in favour of" implies that `rulers` is a sufficient replacement for `max_line_length`.  If you're now saying that's not the case then `rulers` is completely irrelevant to your suggestion of deprecating `max_line_length`.

There are two parts of the EditorConfig project. There's the file format, which is, essentially, a "specification" for standardising editor configuration settings in projects. This specification is everything-unaware. It doesn't know that an editor can trim trailing whitespace or add an empty new line as much as an editor can hard wrap without breaking syntax. Then there are the plugins, that implement the rules. For the most part, EditorConfig plugins can just modify configuration of editors, because the majority of EditorConfig rules are general configuration options anyway. I think it makes sense to consider the specification part the most important part, and the plugins just a way of helping adoption of the specification. When you look at it from this point of view, it doesn't particularly matter whether a setting is syntax-aware or not.

> I think that's the very point this thread is trying to achieve here. I would like it marked as deprecated or removed entirely.

You're missing my point though, you're claiming it's already not officially a rule, but it is on the "complete list of properties".  If you mark it as deprecated then that confirms that it's an official rule.  If you remove it from the list, what happens to all the editors and plugins that already support the rule?  Do the Vim, Emacs and other plugins remove support for it? If that's the case, then you're taking something immensely convenient away, purely for the reason that other editors can't or won't support it.

> I'm a bit confused by this point, because your original post was within the context of vscode,

I think you're confusing this with my posts from the other thread.  In this context, I'm being more general.  I use both Vim and Visual Studio Code, as well as other editors on occasion.

> It seems as though you're expectation is that EditorConfig plugins/extensions should be responsible for tracking each keystroke and responding to them as they hit a specified limit. Do you realize how complex this becomes?

That's not what I'm suggesting in the slightest, and I'm not sure how you came to that conclusion.  I realise that it is difficult for EditorConfig plugins to implement this option, and I would say that leaves three options: ask the editor for support in implementing it, provide a compromise option to users, or just don't implement it.  Option 3 is the one you have elected for with the VS Code plugin, but now you're also trying to have the rule removed from other editors that happily provide this functionality.

You already mentioned the VS Code extension, Rewrap, that provides a hard-wrapping solution.  In the other thread, I wasn't suggesting that this functionality be rolled into the EditorConfig plugin.  I was merely trying to say that I don't think "do nothing, because it's too hard" isn't the best option, and maybe some compromise can be made. That could mean that your plugin *provides an option* to the user to add a ruler at the `max_line_length` value, so that Rewrap can wrap to that value. Or it could mean that the complete set of parsed EditorConfig rules are provided to other extensions via an API or other means, and the Rewrap plugin can be improved to detect this setting and use it automatically without also having to implement an EditorConfig loader and parser.

> As for "plugins that implement hard wrapping" using the ruler as an indicator for hard wrapping? I think this is a horrible idea, because it makes too many assumptions about why the ruler is there in the first place. The most graceful way of handling this is for any such plugin to use the EditorConfig core library that matches the language of the plugin to determine where the hard wrapping should occur.

Plugins that implement hard wrapping provide multiple options for users to suit their preferences.  I'm just speaking of mine, and I like to use the ruler for that purpose because I have no other use for rulers and it is convenient to know that I am reaching the maximum permissible line length as I type code.  Your opinion that "this is a horrible idea" is irrelevant, as it is subjective.  I also disagree that it would be graceful for a plugin to be required to implement EditorConfig core. What would be graceful, like I said in my previous paragraph, would be for an EditorConfig plugin to make what it parses available to other plugins, so that the supporting single EditorConfig rules by such a plugin has a low effort-to-value ratio.

**Comment by jedmao** [comment]
> Your use of "in favour of" implies that `rulers` is a sufficient replacement for `max_line_length`.

"In favor of" means "to be replaced by." To be clear, I am not implying that it at-all provides the same functionality as `max_line_length`; only, that it would be the only rule that has even a slightest relationship to it or at the very least fulfills a need for guidance.

> For the most part, EditorConfig plugins can just modify configuration of editors, because the majority of EditorConfig rules are general configuration options anyway.

Yes, this is what EditorConfig plugins are best at and I would argue that if the editor doesn't provide such functionality, that is where EditorConfig support should end (with exceptions).

> I think it makes sense to consider the specification part the most important part, and the plugins just a way of helping adoption of the specification. When you look at it from this point of view, it doesn't particularly matter whether a setting is syntax-aware or not.

I 100% agree with that statement. I only think it's a bit confusing to plugin developers, thinking they have to somehow get all of the EditorConfig rules to work in the editor, when sometimes that very goal can not only be more trouble than it's worth, but it can be damaging.

> You're taking something immensely convenient away, purely for the reason that other editors can't or won't support it.

Do any editors fully support this feature with syntax-aware support? Because if it's not syntax-aware, I would argue that they are supporting it wrong. If that's the case, they don't have to remove the feature if they don't want, but I'd rather a wrongly-implemented feature be removed than provide dangerous support.

> 1. Ask the editor for support in implementing it.

Agreed.

> 2. Provide a compromise option to users, or just don't implement it.

Agreed.

> Option 3 is the one you have elected for with the VS Code plugin.

I've elected for option 2. Don't implement it. And I have doubts that any editors "happily" provide this functionality. The only way to happily provide this functionality is with a syntax-aware approach, which I doubt they have. In fact, if that's the case, I could easily provide this same functionality in vscode. I just think it would do more harm than good.

> I don't think "do nothing, because it's too hard" isn't the best option, and maybe some compromise can be made.

It's not because it's too hard. It's more of a philosophical argument against whether it should be done at all, as it would require awareness of syntax. EditorConfig should leverage built-in editor functionality and stop when it requires more than that. EditorConfig is agnostic of any particular language or syntax; thus, should not seek to implement syntax-specific features. 

> That could mean that your plugin _provides an option_ to the user to add a ruler at the `max_line_length` value, so that Rewrap can wrap to that value.

I feel like you're not hearing my point on this one, because you keep bringing this up. I already have 3 rulers in my user configuration. If you add a 4th, how would Rewrap or any extension know which one was added by EditorConfig? It wouldn't! You could even have one user-defined ruler and no EditorConfig plugin installed. Would the other plugin still interpret that ruler as a hard width for some reason? As such, the only way to safely support this feature is to leverage the EditorConfig core library, which you can do even for random rules that you defined like `foo = bar`.

> Or it could mean that the complete set of parsed EditorConfig rules are provided to other extensions via an API or other means. The Rewrap plugin can be improved to detect this setting and use it automatically without also having to implement an EditorConfig loader and parser.

I like this idea and it looks like the solution (at least for vscode) is [here](https://code.visualstudio.com/api/references/vscode-api#extensions). But even if the rule weren't an official EditorConfig rule, there's nothing stopping you from using it for extraneous rules. My point is that it doesn't have to be an official rule for you to use EditorConfig as an engine to provide the functionality you need. You can make up any rule you want and it works just the same.

**Comment by jedmao** [comment]
@andyearnshaw see https://github.com/editorconfig/editorconfig-vscode/pull/222

**Comment by ffes** [comment]
Note there is a Visual Studio extension that basically does what you suggest: https://github.com/pharring/EditorGuidelines#editorconfig-support-vs-2017-and-vs-2019-only

It uses the keyword `guidelines`.

**Comment by glen-84** [comment]
> If the editor in question does not support multiple rulers, the first ruler is used.

Perhaps it should be the *widest* ruler is used, i.e. the maximum width "suggested/permitted". Why show a narrower ruler when wider lines are quite possibly "allowed"?

**Comment by swarminglogic** [comment]
First of all, I'd like to immediately apologize if I'm overstepping here, so take this with a grain of salt. I head about this project a while ago and thought *finally*, some seemingly standardized way to enforce the opinionated choices everyone hates to see devolve into a "unproductive discussion". Be that tabs vs spaces, how many, line terminators, and what not. It all boils down to making a choice, and sticking to it.

This also used to be an annoyance once that choice was made. In order for these conventions to be properly followed, we need tools to tell us when we break them. So each IDE would have to be configured according to some README. Easily missed, and a hassle, as each IDE is different. But ok, that is how it had to be done, so one did it. Some editors allows for project level configurations which in some occasions made sense to put into revision control (e.g. `.vscode/settings.json`).

Then, along comes this godsend `EditorConfig`. A somewhat standardized way to say how some things *should* be, and at the same time allowing IDEs, linting tools, and other static code analyzers to pick up on it, and conform. This was all well and good, until I tried using `max_line_length`. It worked out of the box on some IDEs, but not vscode. Which brought me over here, and this issue that advocates the abandoning of an already implemented property by several IDEs in favor of one that does not expresses the same concept, is not mentioned in any standard, and is also not implemented by any IDEs or plugins I came across. Hence my utter confusion.

I get the idea of `rulers` that is presented here. It is also reasonable that the max line length (as defined by a project maintainer), can be visualized by a ruler. It also makes sense to be able to define more rulers at desired char lengths. I personally have yet to come across such a use case, but I don't see a good reason why not, as it's not very confusing what it means. However, placing rulers here and there is by no means the same as defining a max line length, one is a visual cue, the other expresses a code standard.

So I find the whole "controversy" to be unfounded. Or, at least, I don't see how there is any. The problem stated about having to decide how `EditorConfig` should handle it, be that soft, hard, just rulers, etc, has no bearing, because that is not the responsibility of `EditorConfig` to begin with. Here is my takeaway:

> If it is reasonable to assume that a quantifiable or enumerable concept related formatting or code standard to exist for most software projects, and editors could handle this concept on a per-file format basis, then it is **absolutely the exact use case** `EditorConfig` was meant to solve.

Then the question is whether `rulers` is such a concept. I'd argue that yes, it is. I mean, why not?

The other question, is `max_line_length` such a concept? *Absolutely*. In my 11 years as a developer across C, C++, Java, Python, Dart, Js, I've yet worked on a single project where this concept was not only quantified, but its meaning has been unambiguous, and there has been built in support in all tools to enforce this convention. Check, check and check. The only contention has been what that number should be.

So, my suggestion is three-fold:

1. This issue should be closed for all the reasons mentioned.
1. The adoption of `max_line_length` can very well finish it's research phase (https://github.com/editorconfig/editorconfig/wiki/Property-research%3A-maximum-line-length), as it's an OK enough name, and it's already been adopted by various editors.
1. A different issue can be created asking for the adoption of a "rulers" property.

**Comment by swarminglogic** [comment]
(6 months later)

I see discussions have carried on regarding rulers and max length, and whether or not it should soft or hard wrap. And, I think I understand now why there is so much fuzz about it. And this time, allow me to be a bit more presumptuous, and perhaps step on someone's toes. It's not my goal to do so, but I think it'll make what I mean clearer.

The main problem seems to be a lack of clarity in what `EditorConfig` should be responsible for. I'm not sure if my definition earlier left anything unclear, but in case, I'll paraphrase to make it clearer.

> `EditorConfig` (i.e. `.editorconfig`) should give suggestions on enumerable or quantifiable properties related to a project, that can affect collaboration, and help configure any tool that would care to know, be that editors, linters, what not.

**How does this relate to soft or hard wraps?**

Well it certainly should never be EditorConfig that does any of this, so then it depends what the enumerated value suggests, and up to various editors to somehow follow some agreed-upon meaning of it. If there isn't an property established by `EditorConfig` to define a hard-wrap (what I would call "max line length", and which has had the same meaning to anyone I've ever discussed this with), _then there should be one_, and `max_line_length` seems like a good enough name. Should there be something else to hint at where a soft-wrap should be? I'm not sure, I've never cared how my colleagues configure their editor to show the contents, so why should `EditorConfig` care? Is anyone suggestion that `EditorConfig` should set `fontFamily` or `fontSize`? That seems equally irrelevant to me. I'm sure most professional developers are capable of configuring the editor's presentation layer however they want. I've never a single time needed to agree on these things on a team level, as no one's choice affects any one else's. Here is a rule of thumb to check if I care: does it change anything that would be checked in to a centralized repo? If no, I don't care.

**How does this relate to `rulers`?**

Rulers is something that belong to the presentation layer, so as you guessed, I care very little whether it is one of the properties definable by `EditorConfig`. I believe the main problem here originates from people not clearly separating code standards, from how code is presented. That said, it would make a lot of sense for an editor to show a ruler indicating where the `max_line_length` is at, and I don't see a problem with an editor choosing to use this concept. I've never seen multiple rulers be used a single time, especially one that needed to be agreed upon and set in code, but I won't presume to be aware of everyone's use cases.

**Where is the confusion?**

I sincerely believe (and I'm allowing the possibility that I've completely missed the boat on this) that the main problem is not understanding what `EditorConfig` should do. If it's meant to be a way to configure _your_ editor, to how _you_ like to have things, then... well, by all means, we are in for a hefty discussion on a lot of things. I would then also not care about `EditorConfig` project at all, and I would also not be here ranting. It just wouldn't be the tool I need it to be, and, that's alright.

`EditorConfig`, perhaps misleading in its name, should be how to define quantifiable or enumerable configurations that would ameliorate collaboration across a team, and across editors or tools. As such, the most useful attributes it can define, are those that can have an effect with regards to collaboration. Multiple rulers? I mean, I fail to imagine a relevant use case, or see how it would affect my work, but I also don't really see the harm. A max line length? I don't need imagination, every single project I've worked on benefited from agreeing on at least _something_, and I've yet to work on something (serious) where it wasn't defined. Tabs vs spaces, and how many? Same thing.

**The "solution"?**

So, let me continue with my presumptuousness, and give some "objective" solutions and brief summary if this. First order of business would be to clarify what is meant by the project documentation. It reads

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs

If this means what I hope it means, then **`EditorConfig` is a way to suggests quantifiable and/or enumerable properties that can affect collaboration of projects**. If this instead also somehow tries to solve how to configure individual users editors, in particular mixing up _coding style_ with editor presentation layer configurations, then, please make that clear. Nothing I've written in either of my rants is relevant at all, and this project is pretty much useless to what I would like to have.

**The next steps are easy.**

- _Don't prioritize the presentation layer._ It has no effect on the purported use case it's trying to solve. This means the whole discussion of hard and soft wraps are moot. Define `max_line_length`, and you're done. Define something else for the presentation layer, e.g. soft wraps, multiple rulers, font sizes, and then leave it up to the individual teams to then bicker over meaningless values that shouldn't be configured on a project level. _But don't mix it up with code styles_.

</rant>

See you in 6 months.

**Comment by jedmao** [comment]
Very well said. I agree on all points. I think we should close this issue until someone can give a good reason why EC should be at all concerned about the presentation layer.

**Comment by om-ha** [comment]
I am just wondering if it's possible at all to disable hard-wrap entirely on editorconfig level in a way that cascades to common editors?

**Comment by mwerle** [comment]
...one year later...

Rulers are very useful in projects where automated tools can't (correctly) enforce the coding guidelines. In our team we have decided on a soft-line-limit of 80, and a hard-line-limit of 100, with certain exceptions (eg, user-visible strings, URLs), which can go beyond the "hard" limit.  Hence absolutely impossible to get automated tools to enforce these rules.

But humans can and should, both during development and during review.  In this case, having multiple rulers shown in our tools at columns 80 and 100 is very useful. Vim supports it. VSCode supports it. I'm sure many other editors do too.

I fail to see the discussion/controversy here.  

"max_line_length" indicates, if defined, where to (hard) wrap lines. It's up to the tool to implement it correctly. 

"rulers" indicates where tools should show visual cues for humans where lines should be wrapped.  

In neither case should it be up to EditorConfig to actually implement these features.

Furthermore, it is definitely out-of-scope for EditorConfig to specify -how- the rulers should be rendered, just -that- they are.

**Comment by swarminglogic** [comment]
@mwerle, I'm also so confused as to why this is an issue. I see that https://github.com/MaterializeInc/materialize/pull/7761 went ahead and removed `max_line_length`.

Which, is puzzling, since I'm going to guess that it's the most common used property, by far, in `.editorconfig`. So much so, that no one really cares what EC has to say on it, (or since the deprecation, _not_ say on it), and all tooling just does the obvious thing that property suggest it should do.

It's just, weird. The only reason it doesn't really matter, is because `.editorconfig` is just a text file which suggests what editors should do. Seems everyone else managed quite fine to figure out the `max_line_length` that has eluded EC maintainers enough to remove.

- `max_line_length`: Suggests a hard limit for a line length. If this is still unclear, it is meant to suggest a hard wrap. If it is _still_ unclear, just take a little peak at how pretty all editors have chosen to implement this.
- `rulers`: An array that suggests where rulers can be placed

The latter seems like somewhat besides the scope of EC, but it also doesn't help to define things that are obvious and can be useful. That's... the whole point, of EC, right?
