### ISSUE TITLE
UNLOCKED! AutoCrlf support (end_of_line = native)

### ISSUE THREAD

**Issue by dmitriyse** [editorconfig/editorconfig#388]
Please unlock or reopen the issue AutoCrlf support (end_of_line = native)
Do not loose feedback from the community.
If authors made some decision it does not mean that it 100% correct especially with such "closed voting".

Very good suggestion on how to implement this feature is described here:
https://github.com/editorconfig/editorconfig/issues/226#issuecomment-339153692

**Comment by jedmao** [comment]
> Very good suggestion on how to implement this feature is described here:
> [#226 (comment)](https://github.com/editorconfig/editorconfig/issues/226#issuecomment-339153692)

Thanks! ❤️ 

The reason we have a voting system is to ensure that we don't introduce a controversial rule. Even though I'm personally in favor of `end_of_line = native`, I respect the process and the experience of other EditorConfig board members, even if I don't agree with them from time to time.

If you have new arguments to bring to the table, that's one thing, but we've already exhaustively discussed this issue, voted, and the answer was no.

**Comment by xuhdev** [comment]
I mostly agree with @jedmao . I don't think we should unlock the issue, for the following reasons.

Nothing is "100% correct" in designing formats. Every matter is more or less subjective. That's why we have [prescribed rules](https://github.com/editorconfig/editorconfig/wiki/Board-Member) to settle these issues: At some point of time, after extensive discussion (see #226), we have to choose a path to move on with, even if it is not the best choice in some people's opinions.

Is the voting system, "closed" as you condemned, legitimate? This system was ratified by a majority of major contributors (see #277). Why is that sufficient? First, a voting system that lies its outcome on arbitrary users is functionally unviable. Secondly, technically speaking, major contributors at that time exclusively own the copyright of the format design, and they have the right to decide how to organize themselves regarding the future development of the format (I'm not a lawyer and this is not legal advice).

Given the voting rule, it is unethical to reopen on a subject immediately after a voting was held. If this is allowed, then the person who is in control of initiating votings can repeatedly reinitiating until they are satisfied with the outcome of the voting. This would be no different from mobocracy. In addition, within a short amount of time, people's opinions are unlikely to change, and it would be more efficient if we spend our energy on other issues.

**Comment by jedmao** [comment]
Well said, @xuhdev. I'm going to close/lock this issue now for all the reasons stated.
