### ISSUE TITLE
Spec incorrectly prohibits spaces around section-name square brackets

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig#500]
The spec says:
> Section Header: starts with a [ and ends with a ].
> * May not use any non-whitespace characters outside of the surrounding brackets.

However, since the initial commit of `editorconfig-core-test`, such spaces have been allowed: https://github.com/editorconfig/editorconfig-core-test/blob/6c8fe6815b12f96f4b357d610ee1cd8da074880a/parser/whitespace.in#L36-L42 .

The spec should be corrected to match the existing behaviour of the tests.

**Comment by Vampire** [comment]
Actually, while the PR improves the wording, I'd say spec and tests are in sync already regarding this.
The spec forbids non-whitespace outside the brackets, which implies that whitespace is fine, otherwise the spec should say "nothing is allowed".

So imho regarding this issue the PR is only using better wording, explicitly allowing whitespace instead of forbidding non-whitespace. :-)

**Comment by cxw42** [comment]
@Vampire Good point --- I must have not have been thinking clearly when I opened this issue :sweat_smile: .  I'm going to close this ticket and then revisit the PR.
