### ISSUE TITLE
INI file format not further specified

### ISSUE THREAD

**Issue by hakre** [editorconfig/editorconfig#97]
[Current documentation](http://docs.editorconfig.org/en/master/editorconfig-format.html) on the editor config file format has the following founding sentence:

> EditorConfig files use an INI file format in which section names are globs matching filenames in a format accepted by the fnmatch C library.

However the _INI file_ format remains undefined. What is the specification this relates to? What stands INI for?
##

**Comment by JoeRobich** [comment]
@treyhunner, 
Since the [file format documentation](http://docs.editorconfig.org/en/master/editorconfig-format.html#format) has been updated to say 
> EditorConfig files use an INI format that is compatible with the format used by Python ConfigParser Library  

and the [Python ConfigParser](https://docs.python.org/2/library/configparser.html) supports multi-line values
```
key: line 1
line 2
line 3
```
Can I use multi-line values for a custom property and expect it to be supported?

**Comment by jedmao** [comment]
I don’t know why there are more than one specification in the wild, but it was my impression that the single source of truth should be https://editorconfig-specification.readthedocs.io/en/latest/

There, that specific call-out to the ConfigParser library was removed. Makes sense too, because the other cores are not written in Python.

**Comment by JoeRobich** [comment]
@jedmao Interesting how the readthedocs.io specification differs from https://editorconfig.org/#file-format-details . It is unfortunate if it isn't supported because it would be quite useful for some settings.

**Comment by jedmao** [comment]
The ultimate source of truth are [the tests](https://github.com/editorconfig/editorconfig-core-test) which pass for all cores. If you can’t find multiline support in there (and I think you won’t), then it’s not officially supported.

**Comment by jedmao** [comment]
I’m also advocating a single source of truth for the specification, if we can consolidate.

**Comment by JoeRobich** [comment]
> If you can’t find multiline support in there (and I think you won’t), then it’s not officially supported.

Thanks @jedmao. Since all the core properties are simple values there would be no need for multi-line support or tests. However for custom properties there are lots of cases where multi-line would be beneficial. Snippets, Templates, File Headers, etc... 

Let me also voice support for a single unambiguous specification.

**Comment by jedmao** [comment]
FWIW, I was aiming to decouple just the INI parsing aspect of EC into a Rust implementation (for wasm). See https://github.com/jedmao/editorconfig-ini

**Comment by cxw42** [comment]
Now that we have a formal specification (https://editorconfig-specification.readthedocs.io/), can this issue be closed?

**Comment by xuhdev** [comment]
Yes I think so. Closing

**Comment by JoeRobich** [comment]
Maybe the specification on editorconfig.org (https://editorconfig.org/#file-format-details) should be changed to point to the formal specification.
